name: Build

concurrency:
  group: "build"
  cancel-in-progress: false

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        mc-version:
          - { minecraft: "1.20.1", yarn: "1.20.1+build.1", fapi: "0.92.6+1.20.1" }
          - { minecraft: "1.21.1", yarn: "1.21.1+build.1", fapi: "0.116.6+1.21.1" }

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build
        run: ./gradlew build -Pcommit=${{ github.sha }} -Pminecraft_version=${{ matrix.mc-version.minecraft }} -Pyarn_mappings=${{ matrix.mc-version.yarn }} -Pfapi_version=${{ matrix.mc-version.fapi }}

      - name: Archive Build
        uses: actions/upload-artifact@v4
        with:
          name: meteor-client-${{ matrix.mc-version.minecraft }}
          path: build/libs/*.jar
